# Generated by Django 4.2.11 on 2025-11-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardfreedeliveryplace',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='standardshippingcharge',
            name='city',
        ),
        migrations.RemoveField(
            model_name='standardshippingcharge',
            name='per_kg_charge',
        ),
        migrations.AlterField(
            model_name='droplocation',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='droplocation',
            name='district',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='returnproductrequest',
            name='district',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='ExpressShippingPlace',
        ),
        migrations.DeleteModel(
            name='StandardFreeDeliveryCities',
        ),
        migrations.DeleteModel(
            name='StandardFreeDeliveryPlace',
        ),
    ]
