#!/bin/sh
# Wait for Django to be ready
/app/compose/waitforit.sh django:8000 --timeout=60 --strict -- echo "Django is up and running"

# Ensure the Rasa server runs with API enabled and on the specified port
exec rasa run actions --port 5055